### ISSUE TITLE
Gramophony parameters getting lost

### ISSUE THREAD

**Issue by eisbaer23** [martinheterjag/JUCE-Projects#1]
When reloading a project, the parameters return to default...
Win7 64bit, REAPER 6.34 64bit.

**Comment by martinheterjag** [comment]
Thanks for letting me know!

**Comment by martinheterjag** [comment]
I can reproduce the issue with Ableton Live and will start looking at it.

**Comment by martinheterjag** [comment]
I found the issue and solved it for both Gramophony and WaveFolder. I will build and upload the new versions to https://www.kvraudio.com/developer/martinheterjag so you don't need to build the projects yourself to test it.

**Comment by eisbaer23** [comment]
Yep, fixed. \o/
